const STATE_ABBREVIATIONS={AL:"Alabama",AK:"Alaska",AZ:"Arizona",AR:"Arkansas",CA:"California",CO:"Colorado",CT:"Connecticut",DE:"Delaware",FL:"Florida",GA:"Georgia",HI:"Hawaii",ID:"Idaho",IL:"Illinois",IN:"Indiana",IA:"Iowa",KS:"Kansas",KY:"Kentucky",LA:"Louisiana",ME:"Maine",MD:"Maryland",MA:"Massachusetts",MI:"Michigan",MN:"Minnesota",MS:"Mississippi",MO:"Missouri",MT:"Montana",NE:"Nebraska",NV:"Nevada",NH:"New Hampshire",NJ:"New Jersey",NM:"New Mexico",NY:"New York",NC:"North Carolina",ND:"North Dakota",OH:"Ohio",OK:"Oklahoma",OR:"Oregon",PA:"Pennsylvania",RI:"Rhode Island",SC:"South Carolina",SD:"South Dakota",TN:"Tennessee",TX:"Texas",UT:"Utah",VT:"Vermont",VA:"Virginia",WA:"Washington",WV:"West Virginia",WI:"Wisconsin",WY:"Wyoming"};
const STATE_GROUPS={"group-a":{label:"Group A — No AV-specific framework",states:["Alaska","Connecticut","Delaware","Idaho","Indiana","Maryland","Massachusetts","Minnesota","Missouri","New Jersey","Ohio","Oregon","Rhode Island","South Carolina","Virginia","Wisconsin","Wyoming"]},"group-b":{label:"Group B — In-vehicle human safety driver required",states:["Hawaii","Illinois","New York","Vermont"]},"group-c":{label:"Group C — Driverless operation authorized (noncommercial)",states:["Maine","Montana","New Hampshire","New Mexico","North Carolina","Washington"]},"group-d":{label:"Group D — Commercial driverless deployment authorized",states:["Alabama","Arizona","Arkansas","California","Colorado","Florida","Georgia","Iowa","Kansas","Kentucky","Louisiana","Michigan","Mississippi","Nebraska","Nevada","North Dakota","Oklahoma","Pennsylvania","South Dakota","Tennessee","Texas","Utah","West Virginia"]}};
const STATE_GROUP_BY_NAME=new Map(Object.entries(STATE_GROUPS).flatMap(([group,{states}])=>states.map(state=>[state,group])));
if(STATE_GROUP_BY_NAME.size!==50)throw new Error("The AV state classification must contain 50 unique states.");
const PAGE_SIZE=10;
const text=value=>value&&value!=="NA"?value:"Not specified in the source workbook.";
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
const classifyState=record=>STATE_GROUP_BY_NAME.get(record.state);
const categoryLabel=category=>STATE_GROUPS[category].label;
const validSourceLink=source=>{try{const url=new URL(source);return["http:","https:"].includes(url.protocol)?url.href:null}catch{return null}};
const renderEnactmentChart=records=>{
  const statesByYear=new Map();records.filter(record=>record.act&&record.act!=="NA"&&/^\d{4}$/.test(record.year)).forEach(record=>{const year=+record.year;if(!statesByYear.has(year))statesByYear.set(year,[]);statesByYear.get(year).push(record.state)});
  const minYear=Math.min(...statesByYear.keys()),maxYear=Math.max(...statesByYear.keys());let cumulative=0;const values=Array.from({length:maxYear-minYear+1},(_,index)=>{const year=minYear+index,states=[...new Set(statesByYear.get(year)||[])].sort((a,b)=>a.localeCompare(b)),increment=states.length;cumulative+=increment;return{year,states,increment,total:cumulative}});
  const mount=document.querySelector("#enactment-chart"),slider=document.querySelector("#chart-year"),output=document.querySelector("#chart-value"),statesDisplay=document.querySelector("#chart-states");let selected=values.length-1;
  slider.max=values.length-1;
  const draw=()=>{const width=Math.max(320,mount.clientWidth),height=width<600?320:400,left=64,right=24,top=24,bottom=56,plotWidth=width-left-right,plotHeight=height-top-bottom,maxCount=Math.max(...values.map(value=>value.total))+1,x=index=>left+(index/(values.length-1))*plotWidth,y=count=>top+plotHeight-(count/maxCount)*plotHeight,yStep=Math.max(1,Math.ceil(maxCount/4)),yTicks=Array.from({length:Math.floor(maxCount/yStep)+1},(_,index)=>index*yStep),tickCount=width<500?4:6,xTickIndexes=[...new Set(Array.from({length:tickCount},(_,index)=>Math.round(index*(values.length-1)/(tickCount-1))))],path=values.map((value,index)=>`${index?"L":"M"}${x(index)} ${y(value.total)}`).join(" ");
    mount.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="chart-title chart-description"><title id="chart-title">Cumulative bills enacted by year</title><desc id="chart-description">A cumulative line chart from ${minYear} through ${maxYear}. Hover over the plot or use the year slider to inspect the total and yearly increment.</desc><rect class="chart-frame" x="${left}" y="${top}" width="${plotWidth}" height="${plotHeight}"/><g>${yTicks.map(tick=>`<line class="chart-grid" x1="${left}" x2="${width-right}" y1="${y(tick)}" y2="${y(tick)}"/><text class="chart-axis" x="${left-12}" y="${y(tick)+4}" text-anchor="end">${tick}</text>`).join("")}${xTickIndexes.map(index=>`<text class="chart-axis" x="${x(index)}" y="${height-bottom+24}" text-anchor="middle">${values[index].year}</text>`).join("")}</g><path class="chart-line" d="${path}"/><line class="chart-guide" x1="${x(selected)}" x2="${x(selected)}" y1="${top}" y2="${top+plotHeight}"/><g>${values.map((value,index)=>`<circle class="chart-point${index===selected?" selected":""}" data-index="${index}" cx="${x(index)}" cy="${y(value.total)}" r="${index===selected?6:4}"/>`).join("")}</g><text class="chart-axis-title" data-axis="x" x="${left+plotWidth/2}" y="${height-8}" text-anchor="middle">Year</text><text class="chart-axis-title" data-axis="y" x="18" y="${top+plotHeight/2}" text-anchor="middle" transform="rotate(-90 18 ${top+plotHeight/2})">Cumulative bills enacted</text><rect class="chart-hover" x="${left}" y="${top}" width="${plotWidth}" height="${plotHeight}" fill="transparent"/></svg><div class="chart-tooltip" role="tooltip" hidden></div>`;
    const svg=mount.querySelector("svg"),tooltip=mount.querySelector(".chart-tooltip"),update=(index,pointerX,pointerY)=>{selected=Math.max(0,Math.min(values.length-1,index));const value=values[selected];slider.value=selected;output.value=`${value.year} · ${value.total} total (+${value.increment} this year)`;statesDisplay.querySelector("dt").textContent=`States adding bills in ${value.year}`;statesDisplay.querySelector("dd").textContent=value.states.length?value.states.join(", "):"None recorded";svg.querySelectorAll(".chart-point").forEach((point,pointIndex)=>{point.classList.toggle("selected",pointIndex===selected);point.setAttribute("r",pointIndex===selected?"6":"4")});const guide=svg.querySelector(".chart-guide");guide.setAttribute("x1",x(selected));guide.setAttribute("x2",x(selected));if(pointerX!==undefined){tooltip.innerHTML=`<strong>${value.year}</strong><span>${value.total} cumulative</span><span>+${value.increment} this year</span>`;tooltip.style.left=`${Math.max(88,Math.min(mount.clientWidth-88,pointerX))}px`;tooltip.style.top=`${Math.max(70,pointerY-10)}px`;tooltip.hidden=false}};
    const hover=svg.querySelector(".chart-hover");hover.addEventListener("pointermove",event=>{const bounds=svg.getBoundingClientRect(),pointerX=event.clientX-bounds.left,pointerY=event.clientY-bounds.top,svgX=pointerX*(width/bounds.width);update(Math.round(((svgX-left)/plotWidth)*(values.length-1)),pointerX,pointerY)});hover.addEventListener("pointerleave",()=>tooltip.hidden=true);slider.oninput=()=>{tooltip.hidden=true;update(+slider.value)};update(selected)};
  draw();new ResizeObserver(draw).observe(mount);
};

Promise.all([
  fetch("data/regulations.json").then(response=>{if(!response.ok)throw new Error("Regulation data could not be loaded.");return response.json()}),
  fetch("assets/us-states.svg").then(response=>{if(!response.ok)throw new Error("Map could not be loaded.");return response.text()})
]).then(([states,mapMarkup])=>{
  if(states.length!==50||states.some(record=>!STATE_GROUP_BY_NAME.has(record.state)))throw new Error("The regulation dataset does not match the 50-state AV classification.");
  const byState=new Map(states.map(record=>[record.state,record]));
  const stateNames=states.map(record=>record.state);
  const mapMount=document.querySelector("#map"),mapSelect=document.querySelector("#map-state-select"),stateFilter=document.querySelector("#state-filter"),typeFilter=document.querySelector("#type-filter"),tableBody=document.querySelector("#regulation-rows"),resultCount=document.querySelector("#result-count"),previousPage=document.querySelector("#previous-page"),nextPage=document.querySelector("#next-page"),pageStatus=document.querySelector("#page-status");
  const stateOptions=stateNames.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join("");
  mapSelect.innerHTML=stateOptions;stateFilter.insertAdjacentHTML("beforeend",stateOptions);
  renderEnactmentChart(states);
  Object.keys(STATE_GROUPS).forEach(group=>document.querySelector(`#stat-${group}`).textContent=states.filter(record=>classifyState(record)===group).length);
  const tableRecords=states.flatMap(record=>[record.bill&&record.bill!=="NA"?{...record,type:"Bill",instrument:record.bill}:null,record.act&&record.act!=="NA"?{...record,type:"Act",instrument:record.act}:null,record.code&&record.code!=="NA"?{...record,type:"Code",instrument:record.code}:null].filter(Boolean));
  let currentPage=1;
  const renderTable=()=>{const selectedState=stateFilter.value,selectedType=typeFilter.value;const filtered=tableRecords.filter(record=>(selectedState==="all"||record.state===selectedState)&&(selectedType==="all"||record.type===selectedType)),pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));currentPage=Math.min(currentPage,pageCount);const start=(currentPage-1)*PAGE_SIZE,visibleRecords=filtered.slice(start,start+PAGE_SIZE);resultCount.textContent=filtered.length?`${start+1}–${Math.min(start+PAGE_SIZE,filtered.length)} of ${filtered.length} records`:"0 records";tableBody.innerHTML=visibleRecords.length?visibleRecords.map(record=>`<tr><td>${escapeHtml(record.state)}</td><td><span class="type-chip ${escapeHtml(record.type)}">${escapeHtml(record.type)}</span></td><td>${escapeHtml(record.instrument)}</td><td>${escapeHtml(record.year||"—")}</td><td>${escapeHtml(text(record.status))}</td></tr>`).join(""):'<tr><td colspan="5" class="empty-row">No matching records.</td></tr>';pageStatus.textContent=`Page ${currentPage} of ${pageCount}`;previousPage.disabled=currentPage===1;nextPage.disabled=currentPage===pageCount};
  const resetTable=()=>{currentPage=1;renderTable()};
  const setDetail=(stateName,scroll=false)=>{const record=byState.get(stateName);if(!record)return;const category=classifyState(record),categoryElement=document.querySelector("#detail-category");document.querySelector("#detail-state").textContent=record.state;document.querySelector("#detail-status").textContent=text(record.status);document.querySelector("#detail-bill").textContent=text(record.bill);document.querySelector("#detail-act").textContent=text(record.act);document.querySelector("#detail-code").textContent=text(record.code);document.querySelector("#detail-driver").textContent=text(record.driver);document.querySelector("#detail-liability").textContent=text(record.liability);document.querySelector("#detail-commercial").textContent=text(record.commercial);document.querySelector("#detail-regulation").textContent=text(record.regulation);document.querySelector("#detail-procedure").textContent=text(record.procedure);categoryElement.textContent=categoryLabel(category);categoryElement.className=`status-pill ${category}`;mapSelect.value=stateName;document.querySelector("#detail-sources").innerHTML=record.sources.length?record.sources.map((source,index)=>{const link=validSourceLink(source);return link?`<a href="${escapeHtml(link)}" target="_blank" rel="noreferrer">Source ${index+1} ↗</a>`:`<span>${escapeHtml(source)}</span>`}).join(""):"No source link listed.";document.querySelectorAll("#map path").forEach(path=>{path.classList.toggle("active",STATE_ABBREVIATIONS[path.id]===stateName);path.setAttribute("aria-pressed",STATE_ABBREVIATIONS[path.id]===stateName?"true":"false")});document.querySelectorAll("[data-state-shortcut]").forEach(button=>button.classList.toggle("active",button.dataset.stateShortcut===stateName));if(scroll)document.querySelector("#state-detail").scrollIntoView({behavior:"smooth",block:"nearest"})};
  mapMount.innerHTML=mapMarkup;const svg=mapMount.querySelector("svg");svg.setAttribute("viewBox","0 0 959 593");svg.removeAttribute("width");svg.removeAttribute("height");svg.setAttribute("role","group");svg.setAttribute("aria-label","United States four-group AV regulation map");
  mapMount.querySelectorAll("path[id]").forEach(path=>{const stateName=STATE_ABBREVIATIONS[path.id],record=byState.get(stateName);if(!record)return;const category=classifyState(record);path.dataset.category=category;path.setAttribute("role","button");path.setAttribute("tabindex","0");path.setAttribute("aria-label",`View ${stateName} regulation profile, ${categoryLabel(category)}`);path.setAttribute("aria-pressed","false");path.addEventListener("click",()=>setDetail(stateName));path.addEventListener("keydown",event=>{if(["Enter"," "].includes(event.key)){event.preventDefault();setDetail(stateName)}})});const labelGroup=document.createElementNS("http://www.w3.org/2000/svg","g");labelGroup.setAttribute("class","state-abbreviations");labelGroup.setAttribute("aria-hidden","true");mapMount.querySelectorAll("path[id]").forEach(path=>{const box=path.getBBox(),label=document.createElementNS("http://www.w3.org/2000/svg","text");label.setAttribute("class","state-abbreviation");label.setAttribute("x",box.x+box.width/2);label.setAttribute("y",box.y+box.height/2);label.textContent=path.id;labelGroup.append(label)});svg.append(labelGroup);
  mapSelect.addEventListener("change",()=>setDetail(mapSelect.value));stateFilter.addEventListener("change",resetTable);typeFilter.addEventListener("change",resetTable);previousPage.addEventListener("click",()=>{currentPage--;renderTable()});nextPage.addEventListener("click",()=>{currentPage++;renderTable()});document.querySelectorAll("[data-state-shortcut]").forEach(button=>button.addEventListener("click",()=>setDetail(button.dataset.stateShortcut,true)));setDetail("Wisconsin");renderTable();
}).catch(error=>{document.querySelector("#map").innerHTML=`<p class="loading-copy">${escapeHtml(error.message)}</p>`;document.querySelector("#regulation-rows").innerHTML=`<tr><td colspan="5" class="empty-row">${escapeHtml(error.message)}</td></tr>`;document.querySelector("#result-count").textContent="Data unavailable"});
