const STATE_ABBREVIATIONS={AL:"Alabama",AK:"Alaska",AZ:"Arizona",AR:"Arkansas",CA:"California",CO:"Colorado",CT:"Connecticut",DE:"Delaware",FL:"Florida",GA:"Georgia",HI:"Hawaii",ID:"Idaho",IL:"Illinois",IN:"Indiana",IA:"Iowa",KS:"Kansas",KY:"Kentucky",LA:"Louisiana",ME:"Maine",MD:"Maryland",MA:"Massachusetts",MI:"Michigan",MN:"Minnesota",MS:"Mississippi",MO:"Missouri",MT:"Montana",NE:"Nebraska",NV:"Nevada",NH:"New Hampshire",NJ:"New Jersey",NM:"New Mexico",NY:"New York",NC:"North Carolina",ND:"North Dakota",OH:"Ohio",OK:"Oklahoma",OR:"Oregon",PA:"Pennsylvania",RI:"Rhode Island",SC:"South Carolina",SD:"South Dakota",TN:"Tennessee",TX:"Texas",UT:"Utah",VT:"Vermont",VA:"Virginia",WA:"Washington",WV:"West Virginia",WI:"Wisconsin",WY:"Wyoming"};
const PAGE_SIZE=10;
const text=value=>value&&value!=="NA"?value:"Not specified in the source workbook.";
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
const classifyState=record=>{const status=record.status.toLowerCase();const driverless=/driverless operation (?:is )?(?:authorized|allowed|permitted)|allows driverless operation|fully autonomous (?:and )?driverless operation is allowed|fully autonomous vehicles? may operate|driverless-capable vehicles? may operate|driverless vehicles? (?:are )?(?:authorized|allowed)|human driver is not required/.test(status);if(driverless)return"driverless";if(/testing|pilot|permit|conditional|authorized|allowed/.test(status))return"testing";return"limited"};
const categoryLabel=category=>({driverless:"Driverless pathway",testing:"Testing or conditional operation",limited:"Limited framework"})[category];
const validSourceLink=source=>{try{const url=new URL(source);return["http:","https:"].includes(url.protocol)?url.href:null}catch{return null}};

Promise.all([
  fetch("data/regulations.json").then(response=>{if(!response.ok)throw new Error("Regulation data could not be loaded.");return response.json()}),
  fetch("assets/us-states.svg").then(response=>{if(!response.ok)throw new Error("Map could not be loaded.");return response.text()})
]).then(([states,mapMarkup])=>{
  const byState=new Map(states.map(record=>[record.state,record]));
  const stateNames=states.map(record=>record.state);
  const mapMount=document.querySelector("#map"),mapSelect=document.querySelector("#map-state-select"),stateFilter=document.querySelector("#state-filter"),typeFilter=document.querySelector("#type-filter"),tableBody=document.querySelector("#regulation-rows"),resultCount=document.querySelector("#result-count"),previousPage=document.querySelector("#previous-page"),nextPage=document.querySelector("#next-page"),pageStatus=document.querySelector("#page-status");
  const stateOptions=stateNames.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join("");
  mapSelect.innerHTML=stateOptions;stateFilter.insertAdjacentHTML("beforeend",stateOptions);
  document.querySelector("#stat-states").textContent=states.length;
  document.querySelector("#stat-statutes").textContent=states.filter(record=>/^yes/i.test(record.statute)).length;
  document.querySelector("#stat-driverless").textContent=states.filter(record=>classifyState(record)==="driverless").length;
  const tableRecords=states.flatMap(record=>[record.bill&&record.bill!=="NA"?{...record,type:"Bill",instrument:record.bill}:null,record.act&&record.act!=="NA"?{...record,type:"Act",instrument:record.act}:null,record.code&&record.code!=="NA"?{...record,type:"Code",instrument:record.code}:null].filter(Boolean));
  let currentPage=1;
  const renderTable=()=>{const selectedState=stateFilter.value,selectedType=typeFilter.value;const filtered=tableRecords.filter(record=>(selectedState==="all"||record.state===selectedState)&&(selectedType==="all"||record.type===selectedType)),pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));currentPage=Math.min(currentPage,pageCount);const start=(currentPage-1)*PAGE_SIZE,visibleRecords=filtered.slice(start,start+PAGE_SIZE);resultCount.textContent=filtered.length?`${start+1}–${Math.min(start+PAGE_SIZE,filtered.length)} of ${filtered.length} records`:"0 records";tableBody.innerHTML=visibleRecords.length?visibleRecords.map(record=>`<tr><td>${escapeHtml(record.state)}</td><td><span class="type-chip ${escapeHtml(record.type)}">${escapeHtml(record.type)}</span></td><td>${escapeHtml(record.instrument)}</td><td>${escapeHtml(record.year||"—")}</td><td>${escapeHtml(text(record.status))}</td></tr>`).join(""):'<tr><td colspan="5" class="empty-row">No matching records.</td></tr>';pageStatus.textContent=`Page ${currentPage} of ${pageCount}`;previousPage.disabled=currentPage===1;nextPage.disabled=currentPage===pageCount};
  const resetTable=()=>{currentPage=1;renderTable()};
  const setDetail=(stateName,scroll=false)=>{const record=byState.get(stateName);if(!record)return;const category=classifyState(record),categoryElement=document.querySelector("#detail-category");document.querySelector("#detail-state").textContent=record.state;document.querySelector("#detail-status").textContent=text(record.status);document.querySelector("#detail-bill").textContent=text(record.bill);document.querySelector("#detail-act").textContent=text(record.act);document.querySelector("#detail-code").textContent=text(record.code);document.querySelector("#detail-driver").textContent=text(record.driver);document.querySelector("#detail-liability").textContent=text(record.liability);document.querySelector("#detail-commercial").textContent=text(record.commercial);document.querySelector("#detail-regulation").textContent=text(record.regulation);document.querySelector("#detail-procedure").textContent=text(record.procedure);categoryElement.textContent=categoryLabel(category);categoryElement.className=`status-pill ${category}`;mapSelect.value=stateName;document.querySelector("#detail-sources").innerHTML=record.sources.length?record.sources.map((source,index)=>{const link=validSourceLink(source);return link?`<a href="${escapeHtml(link)}" target="_blank" rel="noreferrer">Source ${index+1} ↗</a>`:`<span>${escapeHtml(source)}</span>`}).join(""):"No source link listed.";document.querySelectorAll("#map path").forEach(path=>{path.classList.toggle("active",STATE_ABBREVIATIONS[path.id]===stateName);path.setAttribute("aria-pressed",STATE_ABBREVIATIONS[path.id]===stateName?"true":"false")});document.querySelectorAll("[data-state-shortcut]").forEach(button=>button.classList.toggle("active",button.dataset.stateShortcut===stateName));if(scroll)document.querySelector("#state-detail").scrollIntoView({behavior:"smooth",block:"nearest"})};
  mapMount.innerHTML=mapMarkup;const svg=mapMount.querySelector("svg");svg.setAttribute("viewBox","0 0 959 593");svg.removeAttribute("width");svg.removeAttribute("height");svg.setAttribute("role","group");svg.setAttribute("aria-label","United States regulation map");
  mapMount.querySelectorAll("path[id]").forEach(path=>{const stateName=STATE_ABBREVIATIONS[path.id],record=byState.get(stateName);if(!record)return;path.dataset.category=classifyState(record);path.setAttribute("role","button");path.setAttribute("tabindex","0");path.setAttribute("aria-label",`View ${stateName} regulation profile`);path.setAttribute("aria-pressed","false");path.addEventListener("click",()=>setDetail(stateName));path.addEventListener("keydown",event=>{if(["Enter"," "].includes(event.key)){event.preventDefault();setDetail(stateName)}})});
  mapSelect.addEventListener("change",()=>setDetail(mapSelect.value));stateFilter.addEventListener("change",resetTable);typeFilter.addEventListener("change",resetTable);previousPage.addEventListener("click",()=>{currentPage--;renderTable()});nextPage.addEventListener("click",()=>{currentPage++;renderTable()});document.querySelectorAll("[data-state-shortcut]").forEach(button=>button.addEventListener("click",()=>setDetail(button.dataset.stateShortcut,true)));setDetail("Georgia");renderTable();
}).catch(error=>{document.querySelector("#map").innerHTML=`<p class="loading-copy">${escapeHtml(error.message)}</p>`;document.querySelector("#regulation-rows").innerHTML=`<tr><td colspan="5" class="empty-row">${escapeHtml(error.message)}</td></tr>`;document.querySelector("#result-count").textContent="Data unavailable"});
